import '../styles/globals.css'

import Head from 'next/head';
import {useState, useEffect} from "react";
import {useRouter} from 'next/router';
import "antd/dist/antd.css";

import {userService} from "services";

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  const [authorized, setAuthorized] = useState(false);

  const authCheck = (url) => {
      const publicPaths = ['/login', '/signup'];
      const path = url.split('?')[0];

      if (!userService.userValue && !publicPaths.includes(path)) {
        setAuthorized(false);
        router.push({
          pathname: '/login'
        });
      }
      else {
        setAuthorized(true);
      }
  }

  useEffect(() => {
    authCheck(router.asPath);

    // set authorized to false to hide page content while changing routes
    const hideContent = () => setAuthorized(false);
    router.events.on('routeChangeStart', hideContent);

    // run auth check on route change
    router.events.on('routeChangeComplete', authCheck)

    // unsubscribe from events in useEffect return function
    return () => {
      router.events.off('routeChangeStart', hideContent);
      router.events.off('routeChangeComplete', authCheck);
    }
  }, [])

  return (
      <>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          {
              authorized && <Component {...pageProps} />
          }
      </>
  )
}

export default MyApp
