import '../styles/globals.css'

import Head from 'next/head';
import {useState, useEffect} from "react";
import {useRouter} from 'next/router';
import "antd/dist/antd.css";
import {Nav} from "../components/Nav";

import {userService} from "services";

function MyApp({ Component, pageProps }) {
  const router = useRouter();
  const [authorized, setAuthorized] = useState(false);
  const publicPaths = ['/login', '/signup'];

  const authCheck = (url) => {
      const path = url.split('?')[0];

      if (!userService.userValue && !publicPaths.includes(path)) {
        setAuthorized(false);
        router.push({
          pathname: '/login'
        });
      }
      else {
        setAuthorized(true);
      }
  }

  useEffect(() => {
    authCheck(router.asPath);

    // set authorized to false to hide page content while changing routes
    const hideContent = () => setAuthorized(false);
    router.events.on('routeChangeStart', hideContent);

    // run auth check on route change
    router.events.on('routeChangeComplete', authCheck)

    // unsubscribe from events in useEffect return function
    return () => {
      router.events.off('routeChangeStart', hideContent);
      router.events.off('routeChangeComplete', authCheck);
    }
  }, [])

    const menus = [
        {
            name: "Liste des étudiants",
            path: "/students"
        },
        {
            name: "Liste des inscriptions",
            path: "/registrations"
        },
        {
            name: "Liste des promotions",
            path: "/promotions"
        },
        {
            name: "Gestion des formulaires",
            path: "/forms"
        },
    ]

  return (
      <>
          <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>
          {
              authorized && !publicPaths.includes(router.asPath) && (
                  <div className={"flex"}>
                      <Nav data={menus} />
                      <Component {...pageProps} />
                  </div>
              )
          }
          {
              publicPaths.includes(router.asPath) && <Component {...pageProps} />
          }
      </>
  )
}

export default MyApp
